### ISSUE TITLE
set up github action to check for broken links

### ISSUE THREAD

**Issue by alee** [comses-education/github-starter-course#5]
Followup to #2: set up a GitHub action that automatically checks if links are broken whenever markdown files are pushed to the repository. This should run on pull requests and on the main branch.

GitHub actions are part of what's generally called "continuous integration". Whenever you make changes, automated checks are run against those changes. These automated checks could be unit / integration tests, style guide / formatting, etc. They help you maintain codebase consistency and quality.

For more information, see https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions

Here's one github action that might be worth using for this particular repository:

https://github.com/marketplace/actions/markdown-link-check

**Comment by Krisha100** [comment]
I am working on this
